export const localizedRewriteSegments = {
  account: ["account", "compte", "konto", "tili", "cuenta", "conta"],
  events: [
    "evenementen",
    "evenements",
    "events",
    "veranstaltungen",
    "tapahtumat",
    "eventi",
    "eventos",
    "wydarzenia",
  ],
  category: ["categorie", "category", "kategorie", "kategoria", "categoria"],
  cart: [
    "cart",
    "einkaufswagen",
    "ostoskori",
    "carrello",
    "carrito",
    "winkelwagen",
    "panier",
    "carrinho",
  ],
  legal: ["legal", "lainmukainen", "legale"],
  checkout: [
    "betaling",
    "paiement",
    "payment",
    "bezahlen",
    "maksu",
    "pagamento",
    "pago",
  ],
};
